version: '3.9'
services:
  readme.account.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme.account.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - 27017:27017

    volumes:
      - readme.mongo.account:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:${MONGO_PORT}/?authSource=${MONGO_AUTH_BASE} --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  readme.account.mongo.ui:
    image: mongo-express:1.0.2-20
    restart: always
    container_name: readme.account.mongo.ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@readme.account.mongo:${MONGO_PORT}/

volumes:
  readme.mongo.account:
