version: '3.9'
services:
  readme.account.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme.account.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}

    ports:
      - ${MONGODB_PORT}:27017

    volumes:
      - readme.mongo.account:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/${MONGODB_DATABASE} --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  readme.account.mongo.ui:
    image: mongo-express:1.0.2-20
    restart: always
    container_name: readme.account.mongo.ui

    ports:
      - 8081:8081

    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@readme.account.mongo:27017/

volumes:
  readme.mongo.account:
